project_id = "zzfungtlmdbqwkzrbbeu"

[functions.recommend-items]
verify_jwt = false

[functions.setup-test-data]
verify_jwt = false

[functions.add-sample-photos]
verify_jwt = false

[functions.dodo-checkout]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false
